/* HTTP implementation of the API contract (cloud-back, REST under /management).
   Fill each function in as the backend endpoint lands; pages will not change.
   Shape of every response must match the matching function in ./mock/. */
import axios from 'axios'

export const http = axios.create({ baseURL: (process.env.API_BASE || '') + '/management', withCredentials: true })

const notReady = (name) => () => Promise.reject(new Error(`API ${name} is not implemented on the server yet`))

export const overview = notReady('overview')
export const today = notReady('today')
export const aiBrief = notReady('aiBrief')
export const customers = notReady('customers')
export const customer = notReady('customer')
export const health = notReady('health')
export const segments = notReady('segments')
export const onboarding = notReady('onboarding')
export const revenue = notReady('revenue')
export const sales = notReady('sales')
export const team = notReady('team')
export const funnel = notReady('funnel')
export const retention = notReady('retention')
export const acquisition = notReady('acquisition')
export const features = notReady('features')
export const journey = notReady('journey')
export const bases = notReady('bases')
export const base = notReady('base')
export const quota = notReady('quota')
export const jobs = notReady('jobs')
export const dataHealth = notReady('dataHealth')
export const settings = notReady('settings')
export const search = notReady('search')
export const alerts = notReady('alerts')
export const freshness = notReady('freshness')
export const navBadges = notReady('navBadges')
export const setOwner = notReady('setOwner')
export const addNote = notReady('addNote')
export const removeNote = notReady('removeNote')
export const setTask = notReady('setTask')
export const logAudit = notReady('logAudit')
export const setThresholds = notReady('setThresholds')
export const runCron = notReady('runCron')
export const cancelCron = notReady('cancelCron')
export const setAiFeedback = notReady('setAiFeedback')
export const quickView = notReady('quickView')
export const config = notReady('config')
